version: "3.8"

services:
    postgresdb:
      container_name: postgresdb
      image: postgres
      environment:
        POSTGRES_DB: employeedb
        POSTGRES_USER: compose_postgres
        POSTGRES_PASSWORD: compose_postgres
      restart: on-failure
      ports:
      - "5432:5432"
      expose:
      - 5432

    springboot-ws: 
      container_name: springboot-restful-webservices
      build:
        context: ./
        dockerfile: Dockerfile-springboot
      ports:
      - "8080:8080"
      depends_on:
      - postgresdb
      restart: always